"""issue and comment updated

Revision ID: 00c9f1e79d6c
Revises: '590cd224fe28'
Create Date: 2025-10-19 10:36:46.366727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c9f1e79d6c'
down_revision: Union[str, None] = '590cd224fe28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_types')),
    sa.UniqueConstraint('name', name=op.f('uq_issue_types_name'))
    )
    op.add_column('issue_comments', sa.Column('is_admin_comment', sa.Boolean(), nullable=False))
    op.add_column('issues', sa.Column('subject', sa.String(length=200), nullable=False))
    op.add_column('issues', sa.Column('issue_type_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_issues_issue_type_id_issue_types'), 'issues', 'issue_types', ['issue_type_id'], ['id'])
    op.drop_column('issues', 'title')
    op.drop_column('issues', 'resolution_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('issues', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_issues_issue_type_id_issue_types'), 'issues', type_='foreignkey')
    op.drop_column('issues', 'issue_type_id')
    op.drop_column('issues', 'subject')
    op.drop_column('issue_comments', 'is_admin_comment')
    op.drop_table('issue_types')
    # ### end Alembic commands ###
