"""added conveted key

Revision ID: 076f24d8f587
Revises: '122f400295c1'
Create Date: 2026-01-19 16:02:58.941426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076f24d8f587'
down_revision: Union[str, None] = '122f400295c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('converted_file_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'converted_file_key')
    # ### end Alembic commands ###
