"""added display name

Revision ID: 1003373e4b8d
Revises: '37104f8ccde6'
Create Date: 2025-08-11 12:29:12.411817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1003373e4b8d'
down_revision: Union[str, None] = '37104f8ccde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('display_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'display_name')
    # ### end Alembic commands ###
