"""add

Revision ID: 122f400295c1
Revises: '0ee0d03a124a'
Create Date: 2026-01-14 11:25:22.360741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122f400295c1'
down_revision: Union[str, None] = '0ee0d03a124a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('information', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'information')
    # ### end Alembic commands ###
