"""prompt model fix

Revision ID: 2311788bcba2
Revises: 'a2a51f78cf7e'
Create Date: 2025-06-15 18:39:31.256183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2311788bcba2'
down_revision: Union[str, None] = 'a2a51f78cf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('prompt', sa.String(), nullable=False))
    op.drop_column('prompts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('prompts', 'prompt')
    # ### end Alembic commands ###
