"""Add frontend_texts table update

Revision ID: 35293ef17f76
Revises: 'ef0d272b9ff9'
Create Date: 2025-10-21 11:13:28.273130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35293ef17f76'
down_revision: Union[str, None] = 'ef0d272b9ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
