"""added issues, license and organization updated

Revision ID: 37104f8ccde6
Revises: '809126f510a1'
Create Date: 2025-07-29 18:48:39.141032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37104f8ccde6'
down_revision: Union[str, None] = '809126f510a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Use a constant for the organization foreign-key target to avoid duplicating the literal
ORGANIZATION_FK = 'organization.id'
# Use a constant for the users primary-key foreign-key target
USERS_FK = 'users.user_id'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], [ORGANIZATION_FK], name=op.f('fk_licenses_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_issues_business_id_business')),
    sa.ForeignKeyConstraint(['organization_id'], [ORGANIZATION_FK], name=op.f('fk_issues_organization_id_organization')),
    sa.ForeignKeyConstraint(['reported_by'], [USERS_FK], name=op.f('fk_issues_reported_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    op.create_table('organization_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_organization_agents_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], [USERS_FK], name=op.f('fk_organization_agents_assigned_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], [ORGANIZATION_FK], name=op.f('fk_organization_agents_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_agents'))
    )
    op.create_table('user_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('invitation_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED', name='invitationstatusenum'), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_user_invitations_business_id_business'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], [USERS_FK], name=op.f('fk_user_invitations_invited_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], [ORGANIZATION_FK], name=op.f('fk_user_invitations_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_invitations_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_invitations')),
    sa.UniqueConstraint('invitation_token', name=op.f('uq_user_invitations_invitation_token'))
    )
    op.create_table('issue_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('commented_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['commented_by'], [USERS_FK], name=op.f('fk_issue_comments_commented_by_users')),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_comments_issue_id_issues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_comments'))
    )
    op.add_column('organization', sa.Column('website_url', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('logo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'logo')
    op.drop_column('organization', 'website_url')
    op.drop_table('issue_comments')
    op.drop_table('user_invitations')
    op.drop_table('organization_agents')
    op.drop_table('issues')
    op.drop_table('licenses')
    # ### end Alembic commands ###
