"""added tone, accent to OrganizationAgent

Revision ID: 3e05feacbbe5
Revises: '72b79b589bdd'
Create Date: 2025-10-30 10:47:13.609244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e05feacbbe5'
down_revision: Union[str, None] = '72b79b589bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_agent_preference_tones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_agent_id', sa.UUID(), nullable=False),
    sa.Column('tone_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_agent_id'], ['organization_agents.id'], name=op.f('fk_organization_agent_preference_tones_organization_agent_id_organization_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tone_id'], ['tones.id'], name=op.f('fk_organization_agent_preference_tones_tone_id_tones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_agent_preference_tones'))
    )
    op.add_column('organization_agents', sa.Column('accent_id', sa.UUID(), nullable=True))
    op.add_column('organization_agents', sa.Column('gender_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_organization_agents_accent_id_accents'), 'organization_agents', 'accents', ['accent_id'], ['id'])
    op.create_foreign_key(op.f('fk_organization_agents_gender_id_genders'), 'organization_agents', 'genders', ['gender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_organization_agents_gender_id_genders'), 'organization_agents', type_='foreignkey')
    op.drop_constraint(op.f('fk_organization_agents_accent_id_accents'), 'organization_agents', type_='foreignkey')
    op.drop_column('organization_agents', 'gender_id')
    op.drop_column('organization_agents', 'accent_id')
    op.drop_table('organization_agent_preference_tones')
    # ### end Alembic commands ###
