"""agenst prompts and chat

Revision ID: 4665e87bd519
Revises: '6c84fd97244f'
Create Date: 2025-06-13 19:39:54.146814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4665e87bd519'
down_revision: Union[str, None] = '6c84fd97244f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_prompts_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    op.add_column('user_preferences', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_user_preferences_prompt_id_prompts'), 'user_preferences', 'prompts', ['prompt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_preferences_prompt_id_prompts'), 'user_preferences', type_='foreignkey')
    op.drop_column('user_preferences', 'prompt_id')
    op.drop_table('prompts')
    # ### end Alembic commands ###
