"""updated user profile and added gender table

Revision ID: 590cd224fe28
Revises: 'cb616361b27e'
Create Date: 2025-10-16 17:53:08.715244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '590cd224fe28'
down_revision: Union[str, None] = 'cb616361b27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genders'))
    )
    op.create_table('user_preference_tones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_preference_id', sa.UUID(), nullable=False),
    sa.Column('tone_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tone_id'], ['tones.id'], name=op.f('fk_user_preference_tones_tone_id_tones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_preference_id'], ['user_preferences.id'], name=op.f('fk_user_preference_tones_user_preference_id_user_preferences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preference_tones')),
    sa.UniqueConstraint('user_preference_id', 'tone_id', name='user_pref_tone_unique')
    )
    op.drop_table('reports')
    op.add_column('user_preferences', sa.Column('gender_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('fk_user_preferences_tone_id_tones'), 'user_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_preferences_gender_id_genders'), 'user_preferences', 'genders', ['gender_id'], ['id'])
    op.drop_column('user_preferences', 'tone_id')
    op.add_column('user_profiles', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user_profiles', sa.Column('additional_info', sa.String(length=500), nullable=True))
    op.drop_column('user_profiles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'additional_info')
    op.drop_column('user_profiles', 'date_of_birth')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    op.add_column('user_preferences', sa.Column('tone_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_user_preferences_gender_id_genders'), 'user_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_preferences_tone_id_tones'), 'user_preferences', 'tones', ['tone_id'], ['id'])
    op.drop_column('user_preferences', 'gender_id')
    op.create_table('reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_str', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_reports_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('file_id', name=op.f('uq_reports_file_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('user_preference_tones')
    op.drop_table('genders')
    # ### end Alembic commands ###
