"""file services

Revision ID: 6c84fd97244f
Revises: 'ea539228b65a'
Create Date: 2025-06-11 18:28:55.753223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c84fd97244f'
down_revision: Union[str, None] = 'ea539228b65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.add_column('files', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('files', sa.Column('file_key', sa.String(length=255), nullable=True))
    op.add_column('files', sa.Column('exception', sa.String(length=1024), nullable=True))
    op.alter_column('files', 's3url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 's3url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('files', 'exception')
    op.drop_column('files', 'file_key')
    op.drop_column('files', 'file_type')
    op.create_table('questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    # ### end Alembic commands ###
