"""Add frontend_texts table update 2

Revision ID: 72b79b589bdd
Revises: '35293ef17f76'
Create Date: 2025-10-21 18:40:52.358867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b79b589bdd'
down_revision: Union[str, None] = '35293ef17f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frontend_texts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('selector', sa.String(length=200), nullable=True),
    sa.Column('routeKey', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frontend_texts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frontend_texts')
    # ### end Alembic commands ###
