"""added business and userprofile enhace tables

Revision ID: 809126f510a1
Revises: '48f1595c7fac'
Create Date: 2025-07-24 17:40:53.744705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '809126f510a1'
down_revision: Union[str, None] = '48f1595c7fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Use a constant for the user_profiles foreign-key target to avoid duplicating the literal
USER_PROFILES_FK = 'user_profiles.id'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DO $$ BEGIN CREATE TYPE messagetypeenum AS ENUM ('user', 'assistant'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE audiotypeenum AS ENUM ('user_voice', 'assistant_voice'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE messagestatusenum AS ENUM ('sent', 'delivered', 'read', 'failed'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE conversationstatusenum AS ENUM ('active', 'archived', 'paused'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE rolelevelenum AS ENUM ('SYSTEM', 'ORGANIZATION', 'BUSINESS'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    op.create_table('business',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('business_type', sa.Enum('CORPORATE', 'EDUCATION', name='businesstypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_business_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business'))
    )
    op.create_table('organization_admin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], name=op.f('fk_organization_admin_assigned_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_organization_admin_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_organization_admin_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_admin'))
    )
    op.create_table('employee_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], [USER_PROFILES_FK], name=op.f('fk_employee_profiles_manager_id_user_profiles')),
    sa.ForeignKeyConstraint(['user_profile_id'], [USER_PROFILES_FK], name=op.f('fk_employee_profiles_user_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_profiles')),
    sa.UniqueConstraint('user_profile_id', name=op.f('uq_employee_profiles_user_profile_id'))
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('parent_contact_id', sa.UUID(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_contact_id'], [USER_PROFILES_FK], name=op.f('fk_student_profiles_parent_contact_id_user_profiles')),
    sa.ForeignKeyConstraint(['user_profile_id'], [USER_PROFILES_FK], name=op.f('fk_student_profiles_user_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('user_profile_id', name=op.f('uq_student_profiles_user_profile_id'))
    )
    op.create_table('teacher_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.String(length=50), nullable=True),
    sa.Column('subject_specialization', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('certification', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], [USER_PROFILES_FK], name=op.f('fk_teacher_profiles_user_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_profiles')),
    sa.UniqueConstraint('user_profile_id', name=op.f('uq_teacher_profiles_user_profile_id'))
    )
    op.drop_table('relationship')
    op.alter_column('chat_messages', 'message_type',
               existing_type=postgresql.ENUM('user', 'assistant', name='message_type_enum'),
               type_=sa.Enum('user', 'assistant', name='messagetypeenum'),
               existing_nullable=False, postgresql_using='message_type::text::messagetypeenum')
    op.alter_column('chat_messages', 'audio_type',
               existing_type=postgresql.ENUM('user_voice', 'assistant_voice', name='audio_type_enum'),
               type_=sa.Enum('user_voice', 'assistant_voice', name='audiotypeenum'),
               existing_nullable=True, postgresql_using='audio_type::text::audiotypeenum')
    op.alter_column('chat_messages', 'status',
               existing_type=postgresql.ENUM('sent', 'delivered', 'read', 'failed', name='message_status_enum'),
               type_=sa.Enum('sent', 'delivered', 'read', 'failed', name='messagestatusenum'),
               existing_nullable=False, postgresql_using='status::text::messagestatusenum')
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('active', 'archived', 'paused', name='conversation_status_enum'),
               type_=sa.Enum('active', 'archived', 'paused', name='conversationstatusenum'),
               existing_nullable=False, postgresql_using='status::text::conversationstatusenum')
    op.add_column('organization', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('organization', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('roles', sa.Column('role_level', sa.Enum('SYSTEM', 'ORGANIZATION', 'BUSINESS', name='rolelevelenum'), nullable=False))
    op.add_column('user_profiles', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('user_profiles', sa.Column('assigned_by', sa.UUID(), nullable=True))
    op.add_column('user_profiles', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(op.f('fk_user_profiles_assigned_by_users'), 'user_profiles', 'users', ['assigned_by'], ['user_id'])
    op.create_foreign_key(op.f('fk_user_profiles_business_id_business'), 'user_profiles', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_profiles_business_id_business'), 'user_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_profiles_assigned_by_users'), 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'is_active')
    op.drop_column('user_profiles', 'expires_at')
    op.drop_column('user_profiles', 'assigned_at')
    op.drop_column('user_profiles', 'assigned_by')
    op.drop_column('user_profiles', 'business_id')
    op.drop_column('roles', 'role_level')
    op.drop_column('organization', 'address')
    op.drop_column('organization', 'email')
    op.alter_column('conversations', 'status',
               existing_type=sa.Enum('active', 'archived', 'paused', name='conversationstatusenum'),
               type_=postgresql.ENUM('active', 'archived', 'paused', name='conversation_status_enum'),
               existing_nullable=False)
    op.alter_column('chat_messages', 'status',
               existing_type=sa.Enum('sent', 'delivered', 'read', 'failed', name='messagestatusenum'),
               type_=postgresql.ENUM('sent', 'delivered', 'read', 'failed', name='message_status_enum'),
               existing_nullable=False)
    op.alter_column('chat_messages', 'audio_type',
               existing_type=sa.Enum('user_voice', 'assistant_voice', name='audiotypeenum'),
               type_=postgresql.ENUM('user_voice', 'assistant_voice', name='audio_type_enum'),
               existing_nullable=True)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.Enum('user', 'assistant', name='messagetypeenum'),
               type_=postgresql.ENUM('user', 'assistant', name='message_type_enum'),
               existing_nullable=False)
    op.create_table('relationship',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship'))
    )
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    op.drop_table('employee_profiles')
    op.drop_table('organization_admin')
    op.drop_table('business')

    # Drop the new enum types
    op.execute("DROP TYPE IF EXISTS messagetypeenum")
    op.execute("DROP TYPE IF EXISTS audiotypeenum")
    op.execute("DROP TYPE IF EXISTS messagestatusenum")
    op.execute("DROP TYPE IF EXISTS conversationstatusenum")
    op.execute("DROP TYPE IF EXISTS rolelevelenum")
    # ### end Alembic commands ###
