"""alex chat

Revision ID: 939d343da597
Revises: 'cbfdd6edc7ab'
Create Date: 2025-06-27 08:31:09.256804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '939d343da597'
down_revision: Union[str, None] = 'cbfdd6edc7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('alex_chat_messages', 'message_type',
               existing_type=postgresql.ENUM('user', 'assistant', name='message_type'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alex_chat_messages', 'message_type',
               existing_type=postgresql.ENUM('user', 'assistant', name='message_type'),
               nullable=False)
    # ### end Alembic commands ###
