"""added agent type

Revision ID: cb616361b27e
Revises: '1003373e4b8d'
Create Date: 2025-08-13 13:35:22.719099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb616361b27e'
down_revision: Union[str, None] = '1003373e4b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('type', sa.String(length=50), nullable=True, server_default='predefined'))
    op.add_column('agents', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('categories', sa.Column('type', sa.String(), nullable=False, server_default='both'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type')
    op.drop_column('agents', 'is_active')
    op.drop_column('agents', 'type')
    # ### end Alembic commands ###
