"""alex chat added

Revision ID: cbfdd6edc7ab
Revises: '8460bf974da8'
Create Date: 2025-06-27 11:14:40.604523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfdd6edc7ab'
down_revision: Union[str, None] = '8460bf974da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alex_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('user', 'assistant', name='message_type'), nullable=False),
    sa.Column('device_key', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alex_chat_messages'))
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alex_chat_messages')
    # ### end Alembic commands ###
