"""allow per-agent user preferences

Revision ID: e46859329f8e
Revises: '8ff7d0fe04f3'
Create Date: 2025-06-11 01:07:09.314395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46859329f8e'
down_revision: Union[str, None] = '8ff7d0fe04f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_preferences_user_id'), 'user_preferences', type_='unique')
    op.create_unique_constraint('user_agent_unique', 'user_preferences', ['user_id', 'agent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_agent_unique', 'user_preferences', type_='unique')
    op.create_unique_constraint(op.f('uq_user_preferences_user_id'), 'user_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
