"""added userid fk to files

Revision ID: ea539228b65a
Revises: 'e46859329f8e'
Create Date: 2025-06-11 01:54:52.504138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea539228b65a'
down_revision: Union[str, None] = 'e46859329f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_files_user_id_users'), 'files', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_files_user_id_users'), 'files', type_='foreignkey')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###
