"""Add frontend_texts table

Revision ID: ef0d272b9ff9
Revises: 'cf3816b156f8'
Create Date: 2025-10-21 10:49:52.035262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0d272b9ff9'
down_revision: Union[str, None] = 'cf3816b156f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_attachments_is_deleted'), table_name='issue_attachments')
    op.drop_index(op.f('ix_issue_attachments_issue_id'), table_name='issue_attachments')
    op.drop_index(op.f('ix_issue_attachments_uploaded_by'), table_name='issue_attachments')
    op.drop_constraint(op.f('fk_issue_attachments_uploaded_by_users'), 'issue_attachments', type_='foreignkey')
    op.drop_constraint(op.f('fk_issue_attachments_issue_id_issues'), 'issue_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_issue_attachments_issue_id_issues'), 'issue_attachments', 'issues', ['issue_id'], ['id'])
    op.create_foreign_key(op.f('fk_issue_attachments_uploaded_by_users'), 'issue_attachments', 'users', ['uploaded_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_issue_attachments_uploaded_by_users'), 'issue_attachments', type_='foreignkey')
    op.drop_constraint(op.f('fk_issue_attachments_issue_id_issues'), 'issue_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_issue_attachments_issue_id_issues'), 'issue_attachments', 'issues', ['issue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_issue_attachments_uploaded_by_users'), 'issue_attachments', 'users', ['uploaded_by'], ['user_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_issue_attachments_uploaded_by'), 'issue_attachments', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_issue_attachments_issue_id'), 'issue_attachments', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_attachments_is_deleted'), 'issue_attachments', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
