from __future__ import annotations

from typing import Any, Optional
from pydantic import BaseModel, Field
from prism_inspire.core.log_config import logger


class PRISMDimensions(BaseModel):
    """PRISM Brain Mapping dimension scores (0-100)."""
    gold: int = Field(ge=0, le=100, description="Structured, detail-oriented")
    green: int = Field(ge=0, le=100, description="Empathetic, people-focused")
    blue: int = Field(ge=0, le=100, description="Analytical, data-driven")
    red: int = Field(ge=0, le=100, description="Action-oriented, results-driven")


class BehavioralPreferenceMap(BaseModel):
    """Complete Behavioral Preference Map generated by Aura."""
    user_id: str
    dimensions: PRISMDimensions
    primary_preference: str  # highest dimension
    secondary_preference: str  # second highest
    behavioral_insights: list[str] = Field(default_factory=list)
    communication_preferences: dict[str, Any] = Field(default_factory=dict)
    growth_areas: list[str] = Field(default_factory=list)
    stress_behaviors: list[str] = Field(default_factory=list)
    version: int = 1
    assessed_at: Optional[str] = None

    def to_context_dict(self) -> dict[str, Any]:
        """Convert to a dict suitable for injection as behavioral_context."""
        return {
            "user_id": self.user_id,
            "dimensions": self.dimensions.model_dump(),
            "primary_preference": self.primary_preference,
            "secondary_preference": self.secondary_preference,
            "insights": self.behavioral_insights,
            "communication": self.communication_preferences,
            "growth_areas": self.growth_areas,
        }


class PRISMProfileRetriever:
    """
    Retrieves PRISM assessment data for a user.

    In production, this calls the PRISM API. For now, it provides
    a structured interface that can be backed by database lookup
    or external API call.
    """

    async def get_profile(self, user_id: str) -> Optional[BehavioralPreferenceMap]:
        """
        Retrieve PRISM profile for a user.

        Returns None if the user has not completed a PRISM assessment.
        """
        # TODO: Integrate with actual PRISM API / database
        # For now, return None to indicate no assessment found
        logger.info(f"PRISMProfileRetriever: looking up profile for user {user_id}")
        return None

    async def get_assessment_history(
        self, user_id: str
    ) -> list[BehavioralPreferenceMap]:
        """Retrieve all historical PRISM assessments for growth tracking."""
        logger.info(f"PRISMProfileRetriever: looking up history for user {user_id}")
        return []


def analyze_dimensions(dimensions: PRISMDimensions) -> dict[str, Any]:
    """
    Analyze PRISM dimensions to identify primary/secondary preferences,
    behavioral patterns, and insights.
    """
    scores = {
        "gold": dimensions.gold,
        "green": dimensions.green,
        "blue": dimensions.blue,
        "red": dimensions.red,
    }
    sorted_dims = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    primary = sorted_dims[0][0]
    secondary = sorted_dims[1][0]

    # Generate insights based on dimension balance
    insights = []
    spread = sorted_dims[0][1] - sorted_dims[-1][1]

    if spread <= 15:
        insights.append(
            "You have a well-balanced profile across all four dimensions, "
            "giving you natural versatility in different situations."
        )
    elif spread >= 40:
        insights.append(
            f"You have a strong preference for {_dim_label(primary)} behaviors. "
            f"This is a real strength — and you can also develop flexibility "
            f"in your {_dim_label(sorted_dims[-1][0])} dimension when needed."
        )

    # Primary-secondary interaction insights
    combo_insights = _get_combo_insight(primary, secondary)
    if combo_insights:
        insights.append(combo_insights)

    # Communication preferences
    communication = _get_communication_preferences(primary, secondary)

    # Growth areas (lowest dimensions)
    growth_areas = [
        f"Developing your {_dim_label(dim)} side could help you "
        f"{_growth_suggestion(dim)}"
        for dim, score in sorted_dims[2:]
        if score < 50
    ]

    # Stress behaviors
    stress_behaviors = _get_stress_behaviors(primary)

    return {
        "primary": primary,
        "secondary": secondary,
        "insights": insights,
        "communication": communication,
        "growth_areas": growth_areas,
        "stress_behaviors": stress_behaviors,
    }


def _dim_label(dim: str) -> str:
    """Human-readable label for a PRISM dimension."""
    return {
        "gold": "Gold (structured, detail-oriented)",
        "green": "Green (empathetic, people-focused)",
        "blue": "Blue (analytical, data-driven)",
        "red": "Red (action-oriented, results-driven)",
    }.get(dim, dim)


def _get_combo_insight(primary: str, secondary: str) -> Optional[str]:
    """Insight based on primary-secondary combination."""
    combos = {
        ("gold", "blue"): (
            "Your Gold-Blue combination means you bring both structure and "
            "analytical depth. You're likely excellent at creating systems "
            "that are both organized and data-informed."
        ),
        ("gold", "green"): (
            "Your Gold-Green combination blends structure with empathy. "
            "You likely excel at creating organized environments where "
            "people feel supported and clear about expectations."
        ),
        ("green", "red"): (
            "Your Green-Red combination brings people-awareness and action "
            "together. You likely motivate others while keeping relationships "
            "strong."
        ),
        ("blue", "red"): (
            "Your Blue-Red combination merges analytical thinking with "
            "decisive action. You likely excel at making data-driven "
            "decisions quickly."
        ),
        ("red", "gold"): (
            "Your Red-Gold combination blends drive with discipline. "
            "You likely get results through structured, efficient approaches."
        ),
        ("green", "blue"): (
            "Your Green-Blue combination brings empathy and analysis together. "
            "You likely understand people deeply and can back up your "
            "intuitions with data."
        ),
    }
    key = (primary, secondary)
    reverse_key = (secondary, primary)
    return combos.get(key) or combos.get(reverse_key)


def _get_communication_preferences(primary: str, secondary: str) -> dict[str, str]:
    """Communication preferences based on dimension profile."""
    prefs = {
        "gold": {
            "preferred_style": "structured and detailed",
            "meeting_preference": "agenda-driven with clear action items",
            "feedback_style": "specific, documented, with examples",
            "decision_approach": "methodical with time to review details",
        },
        "green": {
            "preferred_style": "warm and collaborative",
            "meeting_preference": "inclusive with time for discussion",
            "feedback_style": "supportive, in private, balanced",
            "decision_approach": "consensus-building with stakeholder input",
        },
        "blue": {
            "preferred_style": "logical and evidence-based",
            "meeting_preference": "data-focused with clear objectives",
            "feedback_style": "factual, analytical, improvement-focused",
            "decision_approach": "data-driven with thorough analysis",
        },
        "red": {
            "preferred_style": "direct and results-focused",
            "meeting_preference": "brief, action-oriented, outcome-driven",
            "feedback_style": "straightforward, concise, solution-focused",
            "decision_approach": "fast, decisive, bias toward action",
        },
    }
    return prefs.get(primary, prefs["gold"])


def _growth_suggestion(dim: str) -> str:
    """Growth suggestion for a dimension."""
    return {
        "gold": "bring more structure and attention to detail in complex projects",
        "green": "strengthen relationships and read interpersonal dynamics more naturally",
        "blue": "make more data-informed decisions and strengthen analytical reasoning",
        "red": "take more decisive action and increase your pace when needed",
    }.get(dim, "expand your behavioral range")


def _get_stress_behaviors(primary: str) -> list[str]:
    """Stress behaviors associated with a primary dimension."""
    behaviors = {
        "gold": [
            "May become overly rigid or controlling under pressure",
            "Could fixate on details at the expense of the bigger picture",
            "Might resist change or new approaches when stressed",
        ],
        "green": [
            "May avoid conflict or difficult decisions under pressure",
            "Could over-accommodate others at personal expense",
            "Might take criticism too personally when stressed",
        ],
        "blue": [
            "May over-analyze and delay decisions under pressure",
            "Could become detached or overly critical when stressed",
            "Might dismiss emotional factors in favor of pure logic",
        ],
        "red": [
            "May become impatient or steamroll others under pressure",
            "Could make hasty decisions without sufficient input",
            "Might become overly competitive or dismissive when stressed",
        ],
    }
    return behaviors.get(primary, [])
